version: "3"
services:
  app:
    image: oauth_golang:1.18
    build:
      context: ../..
      dockerfile: deploy/docker/golang/Dockerfile
    container_name: oauth_app
    environment:
      DATABASE_USR: oauth_usr
      DATABASE_PWD: DummyPassword1
    ports:
      - "8080:8080"
    networks:
      - oauth_authentication

  database:
    image: oauth_postgres:14
    build:
      context: ../..
      dockerfile: deploy/docker/postgres/Dockerfile
    container_name: oauth_db
    environment:
      POSTGRES_PASSWORD: DummyPassword1
      POSTGRES_USER: oauth_usr
      POSTGRES_DB: oauth
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - oauth_authentication

  cache:
    image: oauth_redis:6
    build:
      context: ../..
      dockerfile: deploy/docker/redis/Dockerfile
    container_name: oauth_cache
    volumes:
      - cache_volume:/data
    networks:
      - oauth_authentication

volumes:
  database_volume:
  cache_volume:

networks:
  oauth_authentication:
    driver: bridge
